id: P008228
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W2PD19199
  title: 'ལེགས་པར་བཤད་པ་གཏམ་གྱི་ཚོགས་ཨུཏྤལ་སྔོན་པོའི་དོ་ཤལ་དྲང་སྲོང་དགྱེས་པའི་མགུལ་རྒྱན། '
  author: ''
  volumes:
    b45a6b1f7f0e465097a80bc4e1446a3a:
      image_group_id: I2PD19211
      title: ''
      volume_number: 1
      total_pages: 196
      base_file: v001.txt
